#pragma config(Motor,  port1,           right_claw,    tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           lift_1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lift_2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           lift_3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           right_chassis, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           left_chassis1, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           left,          tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           lift_5,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lift_6,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          left_claw,     tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"


void pre_auton()
{
	bStopTasksBetweenModes = true;
}



void lift(int speed){
	motor[lift_1] = speed;
	motor[lift_2] = -speed;
	motor[lift_3] = speed;
	motor[lift_5] = speed;
	motor[lift_6] = speed;
}
void claw(int speed){
	motor[right_claw]=speed;
	motor[left_claw]=speed;
}



task autonomous()
{

	lift(100);
	wait10Msec(25);
	lift(0);
	claw(-100);
	wait10Msec(50);
	claw(0);
	lift(-100);
	wait10Msec(100);
	lift(0);
	wait10Msec(100);
	motor[right_chassis]=100;
	motor[left_chassis1]=100;
	wait10Msec(50);
	motor[right_chassis]=0;
	motor[left_chassis1]=0;
}



task usercontrol()
{
	while(true){
		motor[right_chassis] = vexRT(Ch2);
		motor[left_chassis1] = vexRT(Ch3);
		motor[left] = vexRT(Ch3);

		if(vexRT[Btn5U] == true){
			lift(-120);
		}
		else if(vexRT[Btn5D] == true){
			lift(120);
		}
		else{
			lift(0);
		}

		if(vexRT[Btn6U] == true){
			claw(	-100);
		}
		else if(vexRT[Btn6D] == true){
			claw(100);
		}
		else{
			claw(0);
		}
	}
}
