#pragma config(Motor,  port1,           LiftL1M,       tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           DriveL1,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LiftL2M,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           DriveL2,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           ClawL,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           ClawR,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           DriveR2,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           LiftR2M,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           DriveR1,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          LiftR1M,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void
//Claw Void
void Claw(int speed)
{
	motor[ClawL] = speed;
	motor[ClawR] = speed;
}

//Open Claw
void OpenClaw(float time)
{
	Claw(100);
	wait10Msec(10);
}

//Close Claw
void CloseClaw(float time)
{
	Claw(-100);
	wait10Msec(10);
}

//Drive
//Left Drive
void DriveL(int speed)
{
	motor[DriveL1] = speed;
	motor[DriveL2] = speed;
}

//Right Drive
void DriveR(int speed)
{
	motor[DriveR2] = speed;
	motor[DriveR1] = speed;
}

//Both Left and Right Drive
void Drive(int speed)
{
	DriveL(speed);
	DriveR(speed);
}

//Drive Foward
void DriveF(int speed)
{
	Drive(127);
}

//Drive Back
void DriveB(int speed)
{
	Drive(-127);
}

//Turn Right
void TurnR(int speed)
{
	DriveL(80);
	DriveR(-80);
}

//Turn Left
void TurnL(int speed)
{
	DriveL(-80);
	DriveR(80);
}

//Lift
void Lift(int speed)
{
	motor[LiftL1M] = speed;
	motor[LiftL2M] = speed;
	motor[LiftR1M] = speed;
	motor[LiftR2M] = speed;
}

//Lift UP
void LiftUP(int speed)
{
	Lift(100);
}

//Lift DOWN
void LiftDOWN(int speed)
{
	Lift(-100);
}



task main()
{
	while(true){

	lift(127);
	wait10Msec(100);

	drive(127);
	wait10Msec(200);




}
}
