#pragma config(Motor,  port1,           frontright,    tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           liftycableright, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           clawright,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           rightbackdrive, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           rightliftmiddle, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           leftliftmiddle, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           leftbackdrive, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           clawleft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           liftycableleft, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          frontleft,     tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void
//lift void
void lift (int speed)
{
	motor[liftycableright] = speed;
	motor[liftycableleft] = speed;
	motor[rightliftmiddle] = speed;
	motor[leftliftmiddle] = speed;
}

//drive right void
void driver (int speed)
{
	motor[rightbackdrive] = speed;
	motor[frontright] = speed;
}

//drive left void
void drivel (int speed)
{
	motor[leftbackdrive] = speed;
	motor[frontleft] = speed;
}

//All 4 Drives
void drive(int speed)
{
	driver(speed);
	drivel(speed);
}

//claw void
void claw (int speed)
{
	motor[clawright] = speed;
	motor[clawleft] = speed;
}

//close claw
void cclaw (int speed)
{
	claw(-127);
	wait10Msec(10);
}

//open claw
void oclaw (int speed)
{
	claw(
//turn right
void turnr (float time)
	driver(-50);
	drivel(50);
}

//turn left
void turnl (float time)
{
	driver(50);
	drivel(-50);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	while(true){

	lift(80);
	wait10Msec(10);

	lift(0);
	wait10Msec(10);

	drive(-127);
	wait10Msec(10);

	lift(80);
	wait10Msec(10);

	lift(-80)
	wait10Msec(20);

	drive(127);
	wait10Msec(10);

	lift(80);
	wait10Msec(10);

	lift(0);
	wait10Msec(10);

	drive(-127);
	wait10Msec(10);

	lift(80);
	wait10Msec(10);

	lift(-80)
	wait10Msec(20);

	drive(127);
	wait10Msec(10);

	lift(80);
	wait10Msec(10);

	lift(0);
	wait10Msec(10);

	drive(-127);
	wait10Msec(10);

	lift(80);
	wait10Msec(10);

	lift(-80)
	wait10Msec(20);

	drive(127);
	wait10Msec(10);

	lift(80);
	wait10Msec(10);

	lift(0);
	wait10Msec(10);

	drive(-127);
	wait10Msec(10);

	lift(80);
	wait10Msec(10);

	lift(-80)
	wait10Msec(20);

	drive(127);
	wait10Msec(5);

	turnr(10);

	drive(127);
	wait10Msec(5);

	cclaw;

















}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
