#pragma config(Motor,  port1,           rightmotor,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           claw,          tmotorVex393, openLoop)
#pragma config(Motor,  port7,           lift,          tmotorVex393, openLoop)
#pragma config(Motor,  port9,           leftmotor,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// Move forward at 100 power for 1.9 seconds
	motor[rightmotor] =100;
	motor[leftmotor] =100;
	wait10Msec (190);
	
	// Stop the motors for 0.5 seconds
	motor[rightmotor] =0;
	motor[leftmotor] =0;
	wait10Msec (50);
	
	// Do a 180 in 2 seconds
	motor[rightmotor] =-50;
	motor[leftmotor] =50;
	wait10Msec (200);
	
	// Come back at 100 power for 1.9 seconds.......
	motor[rightmotor] =100;
	motor[leftmotor] =100;
	wait10Msec (190);

}
