#pragma config(Motor,  port2,           rightmotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorVex393, openLoop)
#pragma config(Motor,  port7,           lift,          tmotorVex393, openLoop)
#pragma config(Motor,  port10,          leftmotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This is the main part of the program
task main()
{

	// Set the motors on at "100 speed".... in reverse!
	motor[rightmotor] =-100;
	motor[leftmotor] =-100;

	// Let it run for 10 millisecond intervals.... 200 times.... so, 2 seconds!!
        wait10Msec (200);
}
