#pragma config(Motor,  port1,           Rdrive,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port9,           Lrive,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Lrive,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[Rdrive] = vexRT[Ch2];
		motor[Lrive] = vexRT[Ch3];


}
}
