#pragma config(Motor,  port3,           DriveRR,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DriveFR,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           DriveFL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           DriveRL,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive (int speed)
{
	motor[DriveRR] = speed;
	motor[DriveFR] = speed;
	motor[DriveFL] = speed;
	motor[DriveRL] = speed;
}

void DriveR (int speed)
{
	motor[DriveRR] = speed;
	motor[DriveFR] = speed;
}

void DriverL (int speed)
{
	motor[DriveFL] = speed;
	motor[DriveRL] = speed;
}

task main()
{
	while(true)
{



}
}
