#pragma config(Motor,  port1,           ArmMotor,      tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           ClawMotor,     tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()

{
	// Go straight for 0.75 seconds
	motor[rightMotor] = 127;
	motor[leftMotor]  = 127;
	wait1Msec(100);

	// Raise arm
	motor[ArmMotor] = 127;
	wait1Msec(100);

	// Release Claw
	motor[ClawMotor] = -127;
	wait1Msec(50);

	// 	Go back for 0.75 secounds
	motor[rightMotor] = -127;
	motor[leftMotor] = -127;
	wait1Msec(100);

	// bring arm down and unrelease claw
	motor[ArmMotor] = -127;
	motor[ClawMotor] = 127;
	wait1Msec(100);
}

 //Done
