#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           clawMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           leftMotor,     tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Mr. Mayer
// Sept 29, 2015

// This is a basic program for the clawbots

// There are lines of important code
// And there are lines of documentation for us humans....

// Each line of the program is EQUALLY important



// START of main program

// This defines the main procedure/routine/task of the program
// The whole procedure is enclosed in the { and } brackets
task main()
{


        // The main procedure is basically a WHILE loop
	// This loop runs over and over and over.... an endless loop
	// Again, notice the { bracket at the start.... and the } at the end
	while(1 == 1)
	{

	    // Motor control for the two drive motors
	    // This matches up with the left and right joysticks
	    motor[leftMotor] = vexRT[Ch3];
	    motor[rightMotor] = vexRT[Ch2];

	    //Motor Control for the Arm
 	    // If Button "6 UP"  is pressed, then the motor goes full speed fwd (speed is 0 to 127)
 	    // If Button "6 DOWN"  is pressed, then the motor goes full speed rev.
 	    // If Button "6"  is NOT pressed, then the motor speed is zero... stopped.
	    if(vexRT[Btn6U] == 1)
	        {
	          motor[armMotor] = 127;
	        }
	     else if(vexRT[Btn6D] == 1)
	        {
   	       motor[armMotor] = -127;
  	      }
    	 else
   	      {
   	       motor[armMotor] = 0;
    	    }


	    //Motor Control for the Claw ... same logic as the ARM
	    if(vexRT[Btn5U] == 1)
   	      {
     	     motor[clawMotor] = 127;
    	    }
    	    else if(vexRT[Btn5D] == 1)
    	    {
      	    motor[clawMotor] = -127;
    	    }
    	    else
    	    {
	          motor[clawMotor] = 0;
          }


      // Autonomous program option
     if(vexRT[Btn8L] == 1)
      {
    	  // mover straight ahead for 2 sec
        motor[leftMotor] =100;
    	  motor[rightMotor] =100;
    	  wait10Msec (200);

    	  // turn 90 degrees right
        motor[leftMotor] =127;
        motor[rightMotor] =-127;
    	  wait10Msec (100);

    	 // mover straight ahead for 2 sec
       motor[leftMotor] =100;
    	 motor[rightMotor] =100;
    	 wait10Msec (200);

    	 // turn 90 degrees left
       motor[leftMotor] =0;
    	 motor[rightMotor] =70;
    	 wait10Msec (120);
    }
	}

}

// END of main program
