#pragma config(Motor,  port1,           frontright,    tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           liftycableright, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           clawright,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightbackdrive, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           rightliftmiddle, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           leftliftmiddle, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           leftbackdrive, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           clawleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           liftycableleft, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          frontleft,     tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void
//lift void
void lift (int speed)
{
	motor[liftycableright] = speed;
	motor[liftycableleft] = speed;
	motor[rightliftmiddle] = speed;
	motor[leftliftmiddle] = speed;
}

//drive right void
void driver (int speed)
{
	motor[rightbackdrive] = speed;
	motor[frontright] = speed;
}

//drive left void
void drivel (int speed)
{
	motor[leftbackdrive] = speed;
	motor[frontleft] = speed;
}

//claw void
void claw (int speed)
{
	motor[clawright] = speed;
	motor[clawleft] = speed;
}


task main()
{
	while(true){


	//Remote Control
	//For drive Right
	driver(vexRT[Ch3]);

	//For drive Left
	drivel(vexRT[Ch2]);

	//For Claw
	if (vexRT[Btn6DXmtr2] == true)
	{
			motor[clawright] = 127;
			motor[clawleft] = 127;
	}

 else if (vexRT[Btn6UXmtr2] == true)
	{
			motor[clawright] = -127;
			motor[clawleft] = -127;
	}
	else
	{
		claw(0);
	}

	// For lift
   	if (vexRT[Btn5DXmtr2] == true)
	{
		lift(100);
	}

else	if (vexRT[Btn5UXmtr2] == true)
	{
		lift(-100);
	}
	else
	{
		lift(0);
	}






}
}
