#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  Claw,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LiftR,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LiftL,          sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  DriveR,         sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  DriveL,         sensorQuadEncoder)
#pragma config(Sensor, dgtl11, ClawStopper,    sensorTouch)
#pragma config(Motor,  port1,           Claw1,         tmotorVex393HighSpeed_HBridge, openLoop, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port2,           Lift12,        tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port3,           Lift3,         tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port4,           Lift45,        tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, dgtl5)
#pragma config(Motor,  port5,           Lift6,         tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, dgtl5)
#pragma config(Motor,  port6,           DriveRF,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl7)
#pragma config(Motor,  port7,           DriveRR,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl7)
#pragma config(Motor,  port8,           DriveLF,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl9)
#pragma config(Motor,  port9,           DriveLR,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl9)
#pragma config(Motor,  port10,          Claw2,         tmotorVex393HighSpeed_HBridge, openLoop, driveRight, encoderPort, dgtl1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Void for Project D.c"

task main()
{
	while(true){

	//Go forward and dump Cube
	DriveF;
	wait10Msec(20);




}
}
