#pragma config(Motor,  port1,           LiftR3,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           ChassisL1,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           ChassisL2,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           ChassisR1,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           ChassisR2,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           LiftL1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           LiftL2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           LiftL3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LiftR1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          LiftR2,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

//void

#include "Void for Project D.c"

//Main
task main()
{
	while(true)
		{


//Driver Control
motor[ChassisR1] = vexRT[Ch2];
motor[ChassisR2] = vexRT[Ch2];
motor[ChassisL1] = vexRT[Ch3];
motor[ChassisL2] = vexRT[Ch3];

//Lift
//Lift Up Fast
 if(vexRT[Btn5DXmtr2] == true)
{
Lift(125);
}

//Lift Down Fast
else if(vexRT[Btn5UXmtr2] == true)
{
	Lift(-125);
}

//Lift Up Slow
else if(vexRT[Btn7DXmtr2] == true)
{
	Lift(50)
}

//Lift Down slow
else if(vexRT[Btn7UXmtr2] == true)
{
	Lift(-50)
}

}
}
