#pragma config(Motor,  port7,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{ while(1 == 1)

//controller preset
motor[leftMotor] = vexRT[Ch3];
motor[rightMotor] = vexRT[Ch2];

//automatic transmission, press Btn8R
if(vexRT[Btn8R] == 1)
{

//Go straight for 1 sec
motor[leftMotor] = 100;
motor[rightMotor] = 100;
wait10Msec(100);

//Turn 90 degrees clockwise
motor[leftMotor] = 60;
motor[rightMotor] = -60;
wait10Msec(100);

//Go straight for 2 sec
motor[leftMotor] = 100;
motor[rightMotor] = 100;
wait10Msec(200);

//Turn 90 degrees counter clockwise
motor[leftMotor] = -60;
motor[rightMotor] = 60;
wait10Msec(100);

//Go straight for 1 sec
motor[leftMotor] = 100;
motor[rightMotor] = 100;
wait10Msec(100);

//Turn 90 degrees counter clockwise
motor[leftMotor] = -60;
motor[rightMotor] = 60;
wait10Msec(100);

//Go straight for 1 sec
motor[leftMotor] = 100;
motor[rightMotor] = 100;
wait10Msec(100);

//Turn 90 degrees counter clockwise
motor[leftMotor] = -60;
motor[rightMotor] = 60;
wait10Msec(100);

//Go Straight for 1 sec
motor[leftMotor] = 100;
motor[rightMotor] = 100;
wait10Msec(100);

//Turn 90 degrees clockwise
motor[leftMotor] = 60;
motor[rightMotor] = -60;
wait10Msec(100);

//Go straight for 2 sec
motor[leftMotor] = 100;
motor[rightMotor] = 100;
wait10Msec(200);

//Turn 90 degrees clockwise
motor[leftMotor] = 60;
motor[rightMotor] = -60;
wait10Msec(100);

//Stop 2 secs
motor[leftMotor] = 0;
motor[rightMotor] = 0;
wait10Msec(200);

//Go straight full power for 3 secounds
motor[leftMotor] = 127;
motor[rightMotor] = 127;
wait10Msec(300);
}




}
