#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  imeL,           sensorNone)
#pragma config(Sensor, dgtl2,  imeR,           sensorNone)
#pragma config(Sensor, I2C_1,  RBEn,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LBEn,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           Claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RB,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           Arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           MLift2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           MLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LB,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//



int R_Freq = 150;
int R_Batt = 7978;
int P_Freq = R_Freq * (R_Batt / nImmediateBatteryLevel);
// Initial values for Sensors:
// Initial values for IMEs: port 3 = 0  port 9 = 0
//wait1Msec( P_Freq * 1 );		// wait 150

task main()
{

	// 150  Sensors: no change  IMEs: no change
	motor[ port1 ] = 120;
	motor[ port2 ] = 13;
	motor[ port3 ] = 13;
	motor[ port4 ] = -120;
	motor[ port5 ] = -120;
	wait1Msec( P_Freq * 2 );		// wait 300

	// 450  Sensors: no change  IMEs: no change
	motor[ port4 ] = -120;
	motor[ port5 ] = -120;
	wait1Msec( P_Freq * 8 );		// wait 1200

	// 1650  Sensors: no change  IMEs: no change
	motor[ port6 ] = 127;
	motor[ port7 ] = 127;
	wait1Msec( P_Freq * 5 );		// wait 750

	// 2400  Sensors: no change  IMEs: no change
	motor[ port6 ] = 0;
	motor[ port7 ] = 0;
	wait1Msec( P_Freq * 2 );		// wait 300

	// 2700  Sensors: no change  IMEs: no change
	motor[ port2 ] = 127;
	motor[ port3 ] = 127;
	motor[ port8 ] = 127;
	motor[ port9 ] = 127;
	wait1Msec( P_Freq * 14 );		// wait 2100

	// 4800  Sensors: no change  IMEs: no change
	motor[ port2 ] = 1;
	motor[ port3 ] = 1;
	motor[ port8 ] = 1;
	motor[ port9 ] = 1;
	wait1Msec( P_Freq * 4 );		// wait 600

	// 5400  Sensors: no change  IMEs: no change
	motor[ port6 ] = -127;
	motor[ port7 ] = -127;
	wait1Msec( P_Freq * 6 );		// wait 900

	// 6300  Sensors: no change  IMEs: no change
	motor[ port6 ] = 0;
	motor[ port7 ] = 0;
	motor[ port8 ] = -7;
	motor[ port9 ] = -7;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 6450  Sensors: no change  IMEs: no change
	motor[ port2 ] = -127;
	motor[ port3 ] = -127;
	motor[ port4 ] = 127;
	motor[ port5 ] = 127;
	motor[ port8 ] = -127;
	motor[ port9 ] = -127;
	wait1Msec( P_Freq * 4 );		// wait 600

	// 7050  Sensors: no change  IMEs: no change
	motor[ port4 ] = 127;
	motor[ port5 ] = 127;
	wait1Msec( P_Freq * 4 );		// wait 600

	// 7650  Sensors: no change  IMEs: no change
	motor[ port2 ] = -113;
	motor[ port3 ] = -113;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 7800  Sensors: no change  IMEs: no change
	motor[ port1 ] = 12;
	motor[ port2 ] = -58;
	motor[ port3 ] = -58;
	motor[ port8 ] = 1;
	motor[ port9 ] = 1;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 7950  Sensors: no change  IMEs: no change
	motor[ port2 ] = 1;
	motor[ port3 ] = 1;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 8100  Sensors: no change  IMEs: no change
	motor[ port1 ] = -120;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 8250  Sensors: no change  IMEs: no change
	motor[ port2 ] = -85;
	motor[ port3 ] = -85;
	motor[ port8 ] = 79;
	motor[ port9 ] = 79;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 8400  Sensors: no change  IMEs: no change
	motor[ port1 ] = 12;
	motor[ port2 ] = -123;
	motor[ port3 ] = -123;
	motor[ port8 ] = 127;
	motor[ port9 ] = 127;
	wait1Msec( P_Freq * 4 );		// wait 600

	// 9000  Sensors: no change  IMEs: no change
	motor[ port2 ] = -60;
	motor[ port3 ] = -60;
	motor[ port8 ] = 74;
	motor[ port9 ] = 74;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 9150  Sensors: no change  IMEs: no change
	motor[ port2 ] = 18;
	motor[ port3 ] = 18;
	motor[ port8 ] = 1;
	motor[ port9 ] = 1;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 9300  Sensors: no change  IMEs: no change
	motor[ port2 ] = 127;
	motor[ port3 ] = 127;
	motor[ port8 ] = 127;
	motor[ port9 ] = 127;
	wait1Msec( P_Freq * 5 );		// wait 750

	// 10050  Sensors: no change  IMEs: no change
	motor[ port2 ] = 1;
	motor[ port3 ] = 1;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 10200  Sensors: no change  IMEs: no change
	motor[ port2 ] = -62;
	motor[ port3 ] = -62;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 10350  Sensors: no change  IMEs: no change
	motor[ port2 ] = -121;
	motor[ port3 ] = -121;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 10500  Sensors: no change  IMEs: no change
	motor[ port2 ] = 7;
	motor[ port3 ] = 7;
	motor[ port8 ] = 1;
	motor[ port9 ] = 1;
	wait1Msec( P_Freq * 2 );		// wait 300

	// 10800  Sensors: no change  IMEs: no change
	motor[ port2 ] = -17;
	motor[ port3 ] = -17;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 10950  Sensors: no change  IMEs: no change
	motor[ port2 ] = -125;
	motor[ port3 ] = -125;
	motor[ port8 ] = 106;
	motor[ port9 ] = 106;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 11100  Sensors: no change  IMEs: no change
	motor[ port2 ] = 18;
	motor[ port3 ] = 18;
	motor[ port8 ] = 57;
	motor[ port9 ] = 57;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 11250  Sensors: no change  IMEs: no change
	motor[ port2 ] = 1;
	motor[ port3 ] = 1;
	motor[ port8 ] = 7;
	motor[ port9 ] = 7;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 11400  Sensors: no change  IMEs: no change
	motor[ port2 ] = 76;
	motor[ port3 ] = 76;
	motor[ port8 ] = 99;
	motor[ port9 ] = 99;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 11550  Sensors: no change  IMEs: no change
	motor[ port2 ] = 127;
	motor[ port3 ] = 127;
	motor[ port8 ] = 127;
	motor[ port9 ] = 127;
	wait1Msec( P_Freq * 8 );		// wait 1200

	// 12750  Sensors: no change  IMEs: no change
	motor[ port2 ] = 1;
	motor[ port3 ] = 1;
	motor[ port4 ] = -127;
	motor[ port5 ] = -127;
	motor[ port8 ] = 1;
	motor[ port9 ] = 1;
	wait1Msec( P_Freq * 3 );		// wait 450

	// 13200  Sensors: no change  IMEs: no change
	motor[ port4 ] = -127;
	motor[ port5 ] = -127;
	wait1Msec( P_Freq * 4 );		// wait 600

	// 13800  Sensors: no change  IMEs: no change
	motor[ port6 ] = 127;
	motor[ port7 ] = 127;
	wait1Msec( P_Freq * 5 );		// wait 750

	// 14550  Sensors: no change  IMEs: no change
	motor[ port6 ] = 0;
	motor[ port7 ] = 0;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 14700  Sensors: no change  IMEs: no change
	motor[ port2 ] = 73;
	motor[ port3 ] = 73;
	motor[ port8 ] = 127;
	motor[ port9 ] = 127;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 14850  Sensors: no change  IMEs: no change
	motor[ port2 ] = 127;
	motor[ port3 ] = 127;
	wait1Msec( P_Freq * 3 );		// wait 450

	// 15300  Sensors: no change  IMEs: no change
	motor[ port2 ] = 69;
	motor[ port3 ] = 69;
	motor[ port8 ] = -5;
	motor[ port9 ] = -5;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 15450  Sensors: no change  IMEs: no change
	motor[ port2 ] = -124;
	motor[ port3 ] = -124;
	motor[ port8 ] = -124;
	motor[ port9 ] = -124;
	wait1Msec( P_Freq * 3 );		// wait 450

	// 15900  Sensors: no change  IMEs: no change
	motor[ port2 ] = -102;
	motor[ port3 ] = -102;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 16050  Sensors: no change  IMEs: no change
	motor[ port2 ] = 11;
	motor[ port3 ] = 11;
	motor[ port8 ] = 1;
	motor[ port9 ] = 1;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 16200  Sensors: no change  IMEs: no change
	motor[ port6 ] = -127;
	motor[ port7 ] = -127;
	wait1Msec( P_Freq * 4 );		// wait 600

	// 16800  Sensors: no change  IMEs: no change
	motor[ port2 ] = -110;
	motor[ port3 ] = -110;
	motor[ port6 ] = 0;
	motor[ port7 ] = 0;
	motor[ port8 ] = -127;
	motor[ port9 ] = -127;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 16950  Sensors: no change  IMEs: no change
	motor[ port2 ] = -121;
	motor[ port3 ] = -121;
	wait1Msec( P_Freq * 5 );		// wait 750

	// 17700  Sensors: no change  IMEs: no change
	motor[ port2 ] = 13;
	motor[ port3 ] = 13;
	motor[ port8 ] = -28;
	motor[ port9 ] = -28;
	wait1Msec( P_Freq * 1 );		// wait 150

	// 17850  Sensors: no change  IMEs: no change
	motor[ port2 ] = 10;
	motor[ port3 ] = 10;
	motor[ port8 ] = 1;
	motor[ port9 ] = 1;
}
