#pragma config(Motor,  port4,           driverr,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           driverf,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           drivelr,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           drivelf,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void driver (int speed)
{
	motor[driverr] = speed;
	motor[driverf] = speed;
}

void drivel (int speed)
{
	motor[drivelf] = speed;
	motor[drivelr] = speed;
}

task main()
{
	while(true){

	driver(vexRT[Ch2]);
	drivel(vexRT[Ch3]);


}
}
