#pragma config(Sensor, dgtl1,  DriveEncoderL,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  DriveEncoderR,  sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LiftEncoderR,   sensorQuadEncoder)
#pragma config(Motor,  port1,           LiftL1M,       tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           DriveL1,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LiftL2M,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           DriveL2,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           ClawL,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           ClawR,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           DriveR2,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           LiftR2M,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           DriveR1,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          LiftR1M,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define driveL SensorValue[DriveEncoderL]
#define driveR SensorValue[DriveEncoderR]
#define liftR SensorValue[LiftEncoderR]

void left(int speed)
{
	motor[DriveL1] = speed;
	motor[DriveL2] = speed;
}

void right(int speed)
{
	motor[DriveR2] = speed;
	motor[DriveR1] = speed;
}

void lift(int speed)
{
	motor[LiftL1M] = speed;
	motor[LiftL2M] = speed;
	motor[LiftR1M] = speed;
	motor[LiftR2M] = speed;
}

void claw(int speed)
{
	motor[ClawL] = speed;
	motor[ClawR] = speed;
}
//-----------------------------------------------------------------------------------------------------------------------

task main()
{
  while (true)
	{
		left(vexRT(Ch2));
		right(vexRT(Ch3));
//-----------------------------------------------------------------------------------------------------------------------
		if(vexRT[Btn5D] == 1)
		{
			lift(90);
		}
		else if(vexRT[Btn5U] == 1)
		{
			lift(-110);
		}
		else
		{
			lift(0);
		}
//-----------------------------------------------------------------------------------------------------------------------
		if(vexRT[Btn6D] == 1)
		{
			claw(-110);
		}
		else if(vexRT[Btn6U] == 1)
		{
			claw(110);
		}
		else
		{
			claw(0);
		}
	}
}
