#pragma config(Motor,  port1,           Lmogo,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Lclaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Llift1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Llift2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Ldrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Rdrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Rlift2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Rlift1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Rclaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Rmogo,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void
//mogo void
void mogo (int speed)
{
	motor[Lmogo] = speed;
	motor[Rmogo] = speed;
}

//lift void
void lift (int speed)
{
	motor[Llift1] = speed;
	motor[Llift2] = speed;
	motor[Rlift1] = speed;
	motor[Rlift2] = speed;
}

//claw void
void claw (int speed)
{
	motor[Lclaw] = speed;
	motor[Rclaw] = speed;
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
/*
Display Battery Voltage
ROBOTC on VEX 2.0 Cortex
This program uses the Display functions of ROBOTC on the VEX 2.0 Cortex platform.
It will display the value of the main battery on line 0 and backup battery on line 1.

ROBOT CONFIGURATION
MOTORS &amp; SENSORS:
[I/O Port]                    [Name]                            [Type]                                [Description
UART Port 2                    none                                VEX LCD                                VEX LCD Screen
*/

{
 displayLCDCenteredString(0, "!!IN THE ZONE!!");
 wait10Msec(1000);
}
{
 displayLCDCenteredString(0, "TEAM 356C");
 wait1Msec(1000);
}
{
bLCDBacklight = true;                                    // Turn on LCD Backlight
string mainBattery, backupBattery;

while(true)                                                        // An infinite loop to keep the program running until you terminate it
{
clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
clearLCDLine(1);                                            // Clear line 2 (1) of the LCD

//Display the Primary Robot battery voltage
displayLCDString(0, 0, "Primary: ");
sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
displayNextLCDString(mainBattery);

//Display the Backup battery voltage
displayLCDString(1, 0, "Backup: ");
sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
displayNextLCDString(backupBattery);

//Short delay for the LCD refresh rate
wait1Msec(100);
}
}
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {

    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
