#pragma config(Motor,  port1,           rightU,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           rightD,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           leftD,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           leftU,         tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)

//vex remote control preset
motor[rightU] = motor[rightD] = vexRT[Ch2];
motor[leftU] = motor[leftD] = vexRT[Ch3];


//automatic transmission, press Btn8R
if(vexRT[Btn8R] == 1)
{
//move forward for 1 sec
motor[rightU] = 60;
motor[rightD] = 60;
motor[leftU] = 60;
motor[leftD] = 60;
wait10Msec(100);

//turn 90 degrees
motor[rightU] = 60;
motor[rightD] = 60;
motor[leftU] = 60;
motor[leftD] = 60;
wait10Msec(100);

//go forward for 3 secs
motor[rightU] = 100;
motor[rightD] = 100;
motor[leftU] = 100;
motor[leftD] = 100;
wait10Msec(300);

//turn 90 degrees
motor[rightU] = 60;
motor[rightD] = 60;
motor[leftU] = 60;
motor[leftD] = 60;
wait10Msec(100);

//go straight for 2 secs
motor[rightU] = 100;
motor[rightD] = 100;
motor[leftU] = 100;
motor[leftD] = 100;
wait10Msec(200);

//turn 90 degrees
motor[rightU] = 60;
motor[rightD] = 60;
motor[leftU] = 60;
motor[leftD] = 60;
wait10Msec(100);

//go straight for 1 secs
motor[rightU] = 100;
motor[rightD] = 100;
motor[leftU] = 100;
motor[leftD] = 100;
wait10Msec(100);

//turn 90 degrees
motor[rightU] = 60;
motor[rightD] = 60;
motor[leftU] = 60;
motor[leftD] = 60;
wait10Msec(100);

//go straight for 1 secs
motor[rightU] = 100;
motor[rightD] = 100;
motor[leftU] = 100;
motor[leftD] = 100;
wait10Msec(100);

//turn 90 degrees
motor[rightU] = 60;
motor[rightD] = 60;
motor[leftU] = 60;
motor[leftD] = 60;
wait10Msec(100);

//go straight for 2 secs
motor[rightU] = 100;
motor[rightD] = 100;
motor[leftU] = 100;
motor[leftD] = 100;
wait10Msec(200);

//turn 90 degrees
motor[rightU] = 60;
motor[rightD] = 60;
motor[leftU] = 60;
motor[leftD] = 60;
wait10Msec(100);

//go straight for 3 secs full power
motor[rightU] = 127;
motor[rightD] = 127;
motor[leftU] = 127;
motor[leftD] = 127;
wait10Msec(300);

}
//The End



}
