#pragma config(Motor,  port1,           rightU,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           rightD,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           leftD,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           leftU,         tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true)

	//vex remote control preset
	motor[rightU] = vexRT[Ch2];
	motor[rightD] = vexRT[Ch2];
	motor[leftU] = vexRT[Ch3];
	motor[leftD] = vexRT[Ch3];


}
