#pragma config(Motor,  port1,           frontright,    tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           liftycableright, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           clawright,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           rightbackdrive, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           rightliftmiddle, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           leftliftmiddle, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           leftbackdrive, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           clawleft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           liftycableleft, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          frontleft,     tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void
//lift void
void lift (int speed)
{
	motor[liftycableright] = speed;
	motor[liftycableleft] = speed;
	motor[rightliftmiddle] = speed;
	motor[leftliftmiddle] = speed;
}

//drive right void
void driver (int speed)
{
	motor[rightbackdrive] = speed;
	motor[frontright] = speed;
}

//drive left void
void drivel (int speed)
{
	motor[leftbackdrive] = speed;
	motor[frontleft] = speed;
}

//claw void
void claw (int speed)
{
	motor[clawright] = speed;
	motor[clawleft] = speed;
}
